/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3f4947',
        'outline-variant': '#bec9c6',
        'on-surface': '#0b1c30',
        surface: '#f8f9ff',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed-variant': '#00504b',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#a0d0cb',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#79d4cc',
        'tertiary-fixed': '#97f3ea',
        tertiary: '#00433e',
        'primary-fixed': '#abefe8',
        'surface-container-high': '#dce9ff',
        outline: '#6f7977',
        primary: '#00433f',
        'surface-bright': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'error-container': '#ffdad6',
        'inverse-surface': '#213145',
        'tertiary-container': '#005c57',
        'tertiary-fixed-dim': '#7bd6cd',
        'on-secondary-fixed': '#00201e',
        'on-secondary-container': '#3e6c69',
        'surface-container-highest': '#d3e4fe',
        'surface-container': '#e5eeff',
        'secondary-container': '#bbece7',
        'inverse-primary': '#8fd3cc',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-container': '#8ed2cb',
        'on-tertiary-fixed-variant': '#00504b',
        'on-error-container': '#93000a',
        secondary: '#386662',
        'surface-tint': '#216963',
        'on-tertiary-fixed': '#00201e',
        'on-secondary-fixed-variant': '#1e4e4b',
        'surface-dim': '#cbdbf5',
        'primary-fixed-dim': '#8fd3cc',
        'secondary-fixed': '#bbece7',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#00201e',
        'primary-container': '#0d5c57',
        'surface-container-lowest': '#ffffff',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '1.5rem',
        'space-xl': '1.5rem',
        'space-xxs': '0.125rem',
        'space-lg': '1rem',
        'space-xs': '0.25rem',
        'gutter-desktop': '1.25rem',
        'margin-desktop': '1.5rem',
        gutter: '1rem',
        'space-md': '0.75rem',
        'space-2xl': '2rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'headline-xl': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'data-tabular': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'data-metric': ['Inter'],
        'label-lg': ['Inter'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-xl': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-metric': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
